/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal.view;

import java.awt.Dimension;
import javax.swing.JOptionPane;
import proyectofinal.controller.CursoController;
import proyectofinal.controller.MatriculaController;
import java.util.List;
import javax.swing.ListSelectionModel;

public class MainEstudianteFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainEstudianteFrame
     */
    private String username;
    private String nombreCompleto;

    public MainEstudianteFrame(String username, String nombreCompleto) {
        initComponents();
        tablaCursos.setFont(new java.awt.Font("Dialog", 0, 20));
        tablaCursos.setRowHeight(32);
        tablaCursos.getTableHeader().setFont(new java.awt.Font("Dialog", java.awt.Font.BOLD, 20));
        tablaCursos.getTableHeader().setReorderingAllowed(false);
        tablaCursos.setPreferredScrollableViewportSize(new Dimension(600, 200));
        tablaCursos.setFillsViewportHeight(true);

        tablaCursos.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        setResizable(false);
        setSize(690, 467);
        setLocationRelativeTo(null);
        this.username = username;
        this.nombreCompleto = nombreCompleto;
        lblTitulo.setText("Bienvenido/a " + nombreCompleto);
        cargarCursos();
    }

    private void cargarCursos() {
        List<String> cursos = CursoController.obtenerCursos(); // Formato: código|nombre|docente|precio
        String[][] datos = new String[cursos.size()][4];

        for (int i = 0; i < cursos.size(); i++) {
            String[] partes = cursos.get(i).split("\\|");
            datos[i][0] = partes[0];
            datos[i][1] = partes[1];
            datos[i][2] = partes[2];
            datos[i][3] = partes[3];
        }

        String[] titulos = {"Código", "Curso", "Docente", "Precio"};
        tablaCursos.setModel(new javax.swing.table.DefaultTableModel(datos, titulos) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSeleccionar = new javax.swing.JButton();
        btnVerMatricula = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCursos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(690, 467));

        jPanel1.setBackground(new java.awt.Color(242, 240, 235));

        btnSeleccionar.setBackground(new java.awt.Color(33, 206, 148));
        btnSeleccionar.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        btnSeleccionar.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionar.setText("Pagar");
        btnSeleccionar.setBorder(null);
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        btnVerMatricula.setBackground(new java.awt.Color(33, 206, 148));
        btnVerMatricula.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        btnVerMatricula.setForeground(new java.awt.Color(255, 255, 255));
        btnVerMatricula.setText("Ver mis Cursos");
        btnVerMatricula.setBorder(null);
        btnVerMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMatriculaActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("BIENVENIDO");

        tablaCursos.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        tablaCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Curso", "Docente", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCursos.setShowGrid(true);
        tablaCursos.getTableHeader().setResizingAllowed(false);
        tablaCursos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablaCursos);
        if (tablaCursos.getColumnModel().getColumnCount() > 0) {
            tablaCursos.getColumnModel().getColumn(0).setResizable(false);
            tablaCursos.getColumnModel().getColumn(1).setResizable(false);
            tablaCursos.getColumnModel().getColumn(2).setResizable(false);
            tablaCursos.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnVerMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblTitulo)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        int[] filas = tablaCursos.getSelectedRows();
        if (filas.length < 1 || filas.length > 5) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar entre 1 y 5 cursos.");
            return;
        }

        List<String> seleccionados = new java.util.ArrayList<>();
        for (int fila : filas) {
            String codigo = (String) tablaCursos.getValueAt(fila, 0);
            String nombre = (String) tablaCursos.getValueAt(fila, 1);
            String docente = (String) tablaCursos.getValueAt(fila, 2);
            String precio = (String) tablaCursos.getValueAt(fila, 3);
            seleccionados.add(codigo + "|" + nombre + "|" + docente + "|" + precio);
        }

        if (seleccionados.size() < 1 || seleccionados.size() > 5) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar entre 1 y 5 cursos.");
            return;
        }

        double total = 0;
        for (String c : seleccionados) {
            String[] p = c.split("\\|");
            // Esta es la línea clave: reemplaza la coma por punto directamente en la cadena del precio
            total += Double.parseDouble(p[3].replace(',', '.'));
        }
        new PagoFrame(username, nombreCompleto, seleccionados, total).setVisible(true);
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnVerMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMatriculaActionPerformed
        List< String> cursos = MatriculaController.cursosMatriculados(username);

        if (cursos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Aún no tienes cursos matriculados.");
        } else {
            String mensaje = "Cursos matriculados:\n";
            for (String c : cursos) {
                mensaje += "- " + c.split("\\|")[1] + "\n";
            }
            JOptionPane.showMessageDialog(this, mensaje);
        }

    }//GEN-LAST:event_btnVerMatriculaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JButton btnVerMatricula;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tablaCursos;
    // End of variables declaration//GEN-END:variables
}
