/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal.view;

import javax.swing.JOptionPane;
import proyectofinal.controller.MatriculaController;

public class PagoFrame extends javax.swing.JFrame {

    private String username;
    private String nombreCompleto;
    private java.util.List<String> cursos;
    private double total;
    private MainEstudianteFrame ventanaAnterior;

    /**
     * Creates new form PagoFrame
     */
    public PagoFrame(String username, String nombreCompleto, java.util.List<String> cursos, double total) {
        initComponents();
        setResizable(false);
        setSize(690, 467);
        setLocationRelativeTo(null);
        tablaCursos.setFont(new java.awt.Font("Dialog", 0, 20));
        tablaCursos.setRowHeight(32);
        tablaCursos.getTableHeader().setFont(new java.awt.Font("Dialog", java.awt.Font.BOLD, 20));
        tablaCursos.getTableHeader().setReorderingAllowed(false);
        this.username = username;
        this.nombreCompleto = nombreCompleto;
        this.cursos = cursos;
        this.total = total;

        cargarDatos();
    }

    private void cargarDatos() {

        String[][] datos = new String[cursos.size()][3];
        for (int i = 0; i < cursos.size(); i++) {
            String[] p = cursos.get(i).split("\\|"); // código|nombre|docente|precio
            datos[i][0] = p[1];
            datos[i][1] = p[2];
            datos[i][2] = "$" + p[3];
        }

        String[] columnas = {"Curso", "Docente", "Precio"};
        tablaCursos.setModel(new javax.swing.table.DefaultTableModel(datos, columnas) {
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        });

        double subtotal = total / 1.15;
        double iva = total - subtotal;

        lblSubtotal.setText(String.format("Subtotal: $%.2f", subtotal));
        lblIVA.setText(String.format("IVA (15%%): $%.2f", iva));
        lblTotal.setText(String.format("Total: $%.2f", total));
    }

    private void confirmarPago() {
        boolean ok = MatriculaController.matricular(username, cursos);

        if (!ok) {
            JOptionPane.showMessageDialog(this, "Ya estás matriculado en uno de estos cursos");
            return;
        }

        boolean generado = MatriculaController.generarFacturaPDF(username, nombreCompleto, cursos, total);
        if (generado) {
            JOptionPane.showMessageDialog(this, "Matrícula realizada y factura generada exitosamente");
            if (ventanaAnterior != null) {
                ventanaAnterior.setVisible(true);
            }
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error generando la factura");
        }

    }

    private void cancelarPago() {
        int opcion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que quieres cancelar el pago y volver atrás?", "Confirmar Cancelación", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            if (ventanaAnterior != null) {
                ventanaAnterior.setVisible(true);
                System.out.println("LOG: Regresando a la ventana de matrícula para " + username);
            } else {
                System.out.println("LOG: No hay ventana anterior para regresar. Cerrando PagoFrame.");
            }
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        o = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaCursos = new javax.swing.JTable();
        lblSubtotal = new javax.swing.JLabel();
        lblIVA = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(690, 467));

        jPanel1.setBackground(new java.awt.Color(242, 240, 235));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        o.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        o.setForeground(new java.awt.Color(51, 51, 51));
        o.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        o.setText("Confirmar Pago");
        jPanel1.add(o, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 661, -1));

        btnConfirmar.setBackground(new java.awt.Color(33, 206, 148));
        btnConfirmar.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Generar Factura");
        btnConfirmar.setBorder(null);
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 170, 40));

        tablaCursos.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        tablaCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tablaCursos);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 570, 180));

        lblSubtotal.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblSubtotal.setForeground(new java.awt.Color(51, 51, 51));
        lblSubtotal.setText("jLabel1");
        jPanel1.add(lblSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 240, -1));

        lblIVA.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblIVA.setForeground(new java.awt.Color(51, 51, 51));
        lblIVA.setText("jLabel1");
        jPanel1.add(lblIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 250, -1));

        lblTotal.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(51, 51, 51));
        lblTotal.setText("jLabel1");
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 230, -1));

        btnCancelar.setBackground(new java.awt.Color(33, 206, 148));
        btnCancelar.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        confirmarPago();

    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancelarPago();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    /* public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagoFrame().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel o;
    private javax.swing.JTable tablaCursos;
    // End of variables declaration//GEN-END:variables
}
